### ISSUE TITLE
SPARK M2 Lassie Retrievals

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/roadmap#19]
eta: 2023-06-30

Replace the code making HTTP requests to IPFS Gateway with a retrieval client like Lassie.

Important: Retrieval requests from this module should be indistinguishable from “legit” requests made by other actors in the network (e.g. Saturn). Otherwise SPs can prioritise checker requests over regular traffic.

Children:

- [x] Write a Go/FFI shim to start & stop the Lassie HTTP server. Write Rust bindings for this shim and make sure we can use this from Rust! We will need to configure tooling for CI/CD and also write tests! **[5 days]**

  → https://github.com/filecoin-station/rusty-lassie/pull/1

- [x] Integrate Lassie into Zinnia (both `zinnia` and `zinniad`). (Start Lassie on start, stop it on exit.) **[2 day]**
    - We want to configure Lassie to use Module’s CACHE_DIR as the temp dir. Fortunately, there is already such an option exposed.
    
  → https://github.com/filecoin-station/zinnia/pull/243

- [x] Implement Zinnia JS API for retrieving content for a given CID, optionally allowing the caller to specify the address and protocol to use. **[3 days]**
    - E.g. we can add a small `fetch` wrapper that will translate URLs like `ipfs://bafy...` into Lassie HTTP GET requests.
    - Maybe it’s better to create our own API that will allow us to support additional request parameters like the peer address and the protocol to use. This new API can return `fetch` response under the hood.
    
  → https://github.com/filecoin-station/zinnia/pull/243

- [ ] Lassie improvements **[2 days]**
    - Implement authentication - only Zinnia requests should be handled by Lassie. Requests from other clients must be rejected.
      → https://github.com/filecoin-project/lassie/pull/328
    - We want to configure Lassie HTTP mode to not cache blocks between retrieval requests.

- [x] Update SPARK to use the new API https://github.com/filecoin-station/spark/pull/5
- [x] On `zinniad` start, delete all files in Lassie’s temp dir. These files may be created if Station exits Station while a CID retrieval request is in progress.
  → https://github.com/filecoin-station/zinnia/issues/245

**Comment by juliangruber** [comment]
Yes!

https://github.com/filecoin-station/spark-api/blob/2a288f4a1355f25ac7c76d30c50fa79ac87129e1/scripts/top-cids.js#L33

We have protocol and provider multi address available.

**Comment by bajtos** [comment]
> Lassie improvements [2 days]
> 
> Implement authentication - only Zinnia requests should be handled by Lassie. Requests from other clients must be rejected.

Moved to https://github.com/filecoin-station/zinnia/issues/268

> We want to configure Lassie HTTP mode to not cache blocks between retrieval requests.

Moved to https://github.com/filecoin-station/zinnia/issues/269

Closing this milestone as done.

**Comment by juliangruber** [comment]
@bajtos I've removed the newlines between the items, so that starmaps can properly parse the children. See https://filecoinproject.slack.com/archives/C0418TBQ9CH/p1687850671862689?thread_ts=1687165457.518709&cid=C0418TBQ9CH
