### ISSUE TITLE
SPARK joins Reputation DAO

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/roadmap#21]
ETA: 2024-03-31

description: Join the Reputation DAO as another v1 validator.

Resources:
- [How to onboard as a v1 validator](https://www.notion.so/ecosystem-wg/How-to-onboard-as-a-v1-validator-14a752ded5c44552b6ea7a590d590f3c)
- [SP Reputation WG](https://www.notion.so/ecosystem-wg/SP-Reputation-WG-3825b9a7f30a47fab35dab421bbd844b)
- [#reputation-dao in Filecoin Slack](https://filecoinproject.slack.com/archives/C04UT9LM457)

```[tasklist]
### Tasks
- [ ] Add SP `f0xxxxxx` to job templates and/or retrieval measurements
```

**Comment by bajtos** [comment]
A note from a Slack chat:

Reputation DB wants to know the Filecoin SP ID (`f0…`) - what’s the plan for mapping the attestation chain between HTTP and that? Who holds that mapping? How is it trusted?

**Comment by bajtos** [comment]
Reputation Bot is changing the way how they sample SPs, we may want to do the same in SPARK orchestrator.

https://filecoinproject.slack.com/archives/C02GYERNFQU/p1688231482912019
> I received some feedback from some filplus clients and want to propose below changes
> - The chance of a deal being sampled will be proportional to the deal size. So that we don't waste too much compute resources over smaller deals.
> - For each client, currently the chance of its deals being sampled is proportional to number of its active deals which brings a problem that for newer clients with first allocation, it does not get enough samples to get any meaningful retrieval result. I am proposing to give smaller clients more chance to get sampled by multiplying the chance by square root of the total deals made by that client. This means, instead of having 100Tib client being sampled 100x than 1Tib client, it will be only 10x, giving the smaller client 10x chance of being sampled. Side effect of this change is, for per provider retrieval score, it will have a higher weight for deals made by smaller clients.

**Comment by bajtos** [comment]
The script used to upload data from Reputation Bot to Reputation DB:

https://github.com/data-preservation-programs/RetrievalBot/blob/f74a47a34b6b13980f6f7c9db364cca1b0321543/integration/repdao/main.go

**Comment by bajtos** [comment]
There is a discussion about filtering out outliers. It seems important to be able to tell the location of the client that performed the check to detect retrieval checks crossing China's Great Firewall.

More details here: https://filecoinproject.slack.com/archives/C02GYERNFQU/p1688614659971779

**Comment by juliangruber** [comment]
> It seems important to be able to tell the location of the client that performed the check to detect retrieval checks crossing China's Great Firewall.

Yes! This way we can also tell which other regions are crypto (un)friendly, and how latency is distributed

**Comment by juliangruber** [comment]
Shall we start adding this now? Should be a matter of client IP lookup in the spark api

**Comment by bajtos** [comment]
> Shall we start adding this now? Should be a matter of client IP lookup in the spark api

Sure, if we have the bandwidth. 

Otherwise, I think this can wait until we have a better understanding of the high-level scope and timeline for this work.

BTW, if SPARK logs include geo-location info based on the client IP, then we will be able to visualise locations where we have SPARK clients running. (ATM, we have location info for Filecoin Desktop instances only, as provided by Plausible analytics.)

**Comment by bajtos** [comment]
How to onboard as a v1 validator: https://www.notion.so/ecosystem-wg/How-to-onboard-as-a-v1-validator-14a752ded5c44552b6ea7a590d590f3c

**Comment by coreymjames** [comment]
### Update from Caro:

- In terms of transferring (or uploading) the data to Reputation WG, Caro noted that automated/recurring cron jobs (compliant with this schema) suffices for them.
- In other words, they are expecting a 'SPARK transfers the data' and not 'RepDAO pulls data' in terms of operating model. Further details:
   - There's a 50 mb per day upload limit (so as to not flood the db)
   - SPARK can upload aggregated data or sampling

See [SP Reputation WG Schema Requirements](https://data-programs.gitbook.io/reputation/contribute/schema-requirements)
