### ISSUE TITLE
Reduce load on SPs

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/roadmap#52]
As the Station network grows, we put a lot of load on SPs. Some CIDs are being retrieved 1000x a day, which is rather wasteful. SPARK is about retrieval testing not load testing.

Let's improve this.

- [x] Add per-round configuration "tasks per node" (TN) as described in [SPARK tasking v2](https://www.notion.so/pl-strflt/SPARK-tasking-v2-604e26d57f6b4892946525bcb3a77104?pvs=4#ded1cd98c2664a2289453d38e2715643).
- [x] Modify spark checkers to honour this config when calculating delay between retrievals
- [x] Modify spark checkers to fetch to root block only
- Deploy SPARK to Stations
  - [x] publish a new SPARK version
  - [x] publish a new Station Core version
  - [x] publish a new Station Desktop version
- [x] https://github.com/filecoin-station/spark-evaluate/issues/98
- [x] Add a new metric to track how many measurements are submitted for each task + visualise it
- [x] https://github.com/filecoin-station/spark-api/pull/173

**Comment by juliangruber** [comment]
> which is rather hateful

hurtful?

**Comment by bajtos** [comment]
> > which is rather hateful
> 
> hurtful?

I wanted to write _wasteful_, I updated the issue description.

**Comment by bajtos** [comment]
https://github.com/filecoin-station/core/releases/tag/v16.3.0
