### ISSUE TITLE
Reduce RAM size of Spark VM's

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/roadmap#63]
Scale down Fly.io VM instances to match the amount of RAM needed by the current network size.

- [x] spark-api
- [x] spark-db
- [x] spark-evaluate
- [x] spark-publish
- [x] Shrink spark-db volumes from 500GB to 50GB (we are currently using ~22GB).

**Comment by bajtos** [comment]
Reduced spark-db VM RAM from 4GB down to 1GB.

```
fly scale memory 1024 -a spark-db
```

**Comment by bajtos** [comment]
Scaled down spark-evaluate from shared-cpu-4x:4GB to shared-cpu-1x:2GB

```
fly scale vm shared-cpu-1x --vm-memory 2048 -a spark-evaluate
```

**Comment by bajtos** [comment]
Shrinked spark-db volumes from 500GB down to 50GB. This was a quite involved process.

Create a new smaller volume

```
fly -a spark-db volume create -s 50 -r cdg pg_data
```

Clone the PG replica machine and attach it to the new volume

```
fly machine clone -a spark-db --attach-volume vol_p4mel7qjke7eey3r --region cdg 2874de7f654328
```

Stop the old replica (I used the web UI)

Failover to new replica with small volume

```
fly pg failover -a spark-db
```

Delete old replica

```
fly machine destroy -a spark-db 2874de7f654328
```

Create another small volume and another VM clone

```
fly -a spark-db volume create -s 50 -r cdg pg_data
fly machine clone -a spark-db --attach-volume vol_d42dlldoo3n00n8v --region cdg e8247eef066638
```

Delete the former leader with large volume

```
fly machine stop -a spark-db e28657eea65e68
fly machine destroy -a spark-db e28657eea65e68
```

**Comment by juliangruber** [comment]
Thank you for documenting the process 👏
