### ISSUE TITLE
Bacalhau Worker Module without Incentives

### ISSUE THREAD

**Issue by patrickwoodhead** [filecoin-station/roadmap#7]
eta: 2023-06-01

description: By the end of February 2023, Station will ship with a Bacalhau worker module. Station users will not get paid for the jobs performed by the Bacalhau worker as the Bacalhau incentive model is not yet developed.

Children:
- [x] https://github.com/filecoin-project/bacalhau/issues/1779
- [x] https://github.com/filecoin-project/bacalhau/issues/1768
- [x] https://github.com/filecoin-project/bacalhau/issues/1767
- [x] https://github.com/filecoin-project/bacalhau/issues/1780
- [x] https://github.com/filecoin-project/bacalhau/issues/1558
- [x] https://github.com/filecoin-station/filecoin-station/issues/535

**Comment by patrickwoodhead** [comment]
Updated ETA to end of February due to delays from the Bacalhau team

**Comment by juliangruber** [comment]
Added `children` in order to get a progress bar in starmaps

**Comment by quickhatche** [comment]
Hey, What is the status of this? Should this be marked as done since the ETA was supposed to be end of Feb? Need to know if ETA status needs to be updated accordingly.

**Comment by juliangruber** [comment]
I think some new requirements surfaced in https://filecoinproject.slack.com/archives/C046BBT15FG/p1679917536031869, which to my knowledge haven't been captured in issues yet. I have asked for an update there. What do you think about updating the ETA to May?

**Comment by juliangruber** [comment]
Sorry, done
