### ISSUE TITLE
Track additional SaaS metrics for the Station network

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/roadmap#91]
Traditional SaaS metrics like churn, monthly active users

Additional metrics to implement:

- [x] Customer churn rate - API
- [x] Customer churn rate - Dashboard
- [x] Customer monthly growth rate (CMGR) - API
- [x] Customer monthly growth rate (CMGR) - Dashboard
- [x] Customer Retention Rate - API
- [x] Customer Retention Rate - Dashboard

**Comment by bajtos** [comment]
Done.

https://bajtos.grafana.net/public-dashboards/9af156c3266d4d8384385623d0d2a76c?orgId=1
<img width="658" alt="Screenshot 2024-04-23 at 17 12 57" src="https://github.com/filecoin-station/roadmap/assets/1140553/dd19da25-1469-456c-a0b2-d48702224d72">
